name: Deploy Python Application to AWS Lambda
on:
    push:
        branches: [ main ]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              name: Checkout code
            
            - uses: actions/setup-python@v4
              name: Set up Python
              with:
                python-version: '3.8'
                
            - name: Install dependencies
              run: |
                pip install --upgrade pip
                pip install -r requirements.txt
                pip install awscli
            - name: Package Lambda function
              run: |
                mkdir package
                ls
                cp -r . package/
                cd package
                zip -r ../function.zip .
            - name: Deploy to Lambda
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: ${{ secrets.AWS_REGION }}
                LAMBDA_FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}
              run: |
                aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file
                fileb://function.zip --publish --region $AWS_REGION